"""
02_build_catalog.py

Purpose
-------
Two jobs, both prerequisites before we can compute an SN-position-centred,
redshift-dependent aperture (Section 2.2.3 logic):

  (1) Parse each FITS filename to recover the SN name, filter, and the
      telescope the stack came from. Your 00_inspect_headers.py run showed
      the header has no FILTER keyword, but the filename encodes it
      directly, e.g.:
          ASAS14ad_B_comb_dup.fits  ->  object=ASAS14ad, filter=B, telescope=duPont
          ASAS14hu_V_comb_swo.fits  ->  object=ASAS14hu, filter=V, telescope=Swope

      CSP imaging was carried out with two telescopes at Las Campanas
      Observatory: the 1m Swope telescope ('swo') and the 2.5m du Pont
      telescope ('dup') (Hamuy et al. 2006, PASP, 118, 2). We keep this as
      its own field because the two telescopes have different plate scales
      and PSF behaviour, both of which feed directly into the local-aperture
      calculation in Section 2.2.3 of Kelsey et al. (2021).

  (2) Look up the host-galaxy redshift for each unique SN name via NED
      (NASA/IPAC Extragalactic Database), using astroquery. This mirrors
      how CSP-II's own data release papers source their redshifts (Phillips
      et al. 2019, PASP, report the CSP-II Hubble-flow sample spans
      0.027 < z < 0.137) -- i.e. redshift is looked up from a maintained
      extragalactic catalog, not measured from these particular images.

Requirements
------------
    pip install astroquery

Usage
-----
    python 02_build_catalog.py --data-dir "D:\\Thesis\\pd\\CSPAll" --out-csv results\\sn_catalog.csv

Notes
-----
- NED queries require an internet connection and can occasionally time out
  or fail for a given name (e.g. ambiguous name resolution, or the object
  is catalogued under its IAU name -- e.g. "SN 2014ad" -- rather than its
  ASAS-SN survey name). Any failures are logged, not silently dropped, so
  you can manually resolve a handful of stragglers from the CSP-II paper's
  Table 1 directly if needed.
"""

from __future__ import annotations

import argparse
import csv
import re
import time
from pathlib import Path

FILENAME_PATTERN = re.compile(
    r"^(?P<object>.+?)_(?P<filter>[A-Za-z]+)_comb_(?P<telescope>dup|swo)\.fits$",
    re.IGNORECASE,
)

TELESCOPE_NAMES = {"dup": "duPont", "swo": "Swope"}


def parse_filename(path: Path):
    """Extract SN name, filter, and telescope from a filename such as
    ASAS14ad_B_comb_dup.fits or ASAS14hu_V_comb_swo.fits."""
    m = FILENAME_PATTERN.match(path.name)
    if not m:
        return None
    tel_code = m.group("telescope").lower()
    return {
        "file": str(path),
        "object": m.group("object"),
        "filter": m.group("filter").upper(),
        "telescope": TELESCOPE_NAMES.get(tel_code, tel_code),
    }


def generate_alt_names(object_name: str) -> list[str]:
    """
    Generate IAU-style alternate names for a CSP object name, so that
    survey-internal designations have a chance of resolving in NED.

    NED's name interpreter is a strict parser, not a fuzzy search: it
    expects the object's registered designation exactly as catalogued.
    Two systematic mismatches show up in this dataset:

      1. ASAS-SN survey names (e.g. "ASAS14ad") are not IAU SN
         designations at all -- the object may be catalogued under
         its IAU name instead (e.g. "SN2014ad").
      2. CSP filenames sometimes preserve the historical two-digit-year
         shorthand (e.g. "SN04dt"), but NED requires the full four-digit
         year ("SN2004dt"). This is the single largest source of
         resolution failures in this catalog -- confirmed by checking
         the NED error messages returned for this sample, where every
         "not currently recognized" failure traced back to a two-digit
         year name.

    Both fixes are safe here because CSP-I/II observations span
    2004-2015 only, so "YY" unambiguously means "20YY" (there is no
    19YY object in this dataset).
    """
    alts = []

    # Case 1: ASAS-SN internal name -> candidate IAU name
    m_asas = re.match(r"ASAS(\d{2})([a-zA-Z]+)", object_name)
    if m_asas:
        alts.append(f"SN20{m_asas.group(1)}{m_asas.group(2)}")

    # Case 2: two-digit-year SN name -> full four-digit-year SN name
    m_short_year = re.match(r"^SN(\d{2})([A-Za-z]+)$", object_name)
    if m_short_year:
        alts.append(f"SN20{m_short_year.group(1)}{m_short_year.group(2)}")

    return alts


def query_ned_redshift(object_name: str, alt_names=None, max_retries: int = 3):
    """
    Query NED for a redshift given an object name. Tries the given name
    first, then any alternates generated by generate_alt_names().

    Each name is retried up to `max_retries` times with exponential
    backoff (2s, 4s, 8s, ...) specifically on network/timeout errors --
    a timeout is transient and worth retrying, whereas a clean
    "name not recognized" response from NED is not (retrying won't fix
    a name NED has already told us it can't parse).

    Returns (redshift, resolved_name, error_message).
    """
    try:
        from astroquery.ipac.ned import Ned
    except ImportError as e:
        raise SystemExit(
            "astroquery is not installed. Run: pip install astroquery"
        ) from e

    names_to_try = [object_name] + (alt_names or [])
    last_error = ""
    for name in names_to_try:
        for attempt in range(max_retries):
            try:
                result_table = Ned.query_object(name)
                if result_table is not None and len(result_table) > 0:
                    z = result_table["Redshift"][0]
                    if z is not None and str(z) not in ("--", "masked", ""):
                        return float(z), name, ""
                break  # query succeeded but had no usable redshift; try next name
            except Exception as e:  # noqa: BLE001
                last_error = f"{name}: {e}"
                is_timeout = "timed out" in str(e).lower() or "timeout" in str(e).lower()
                if is_timeout and attempt < max_retries - 1:
                    time.sleep(2 ** (attempt + 1))  # 2s, 4s, 8s
                    continue
                break  # non-timeout error, or retries exhausted -- move to next name
        time.sleep(1)  # be polite to the NED service between distinct names
    return None, None, last_error


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data-dir", required=True, type=Path)
    parser.add_argument("--out-csv", required=True, type=Path)
    parser.add_argument("--skip-ned", action="store_true",
                         help="Only parse filenames; skip the (slow) NED redshift lookup.")
    args = parser.parse_args()

    fits_files = sorted(
        list(args.data_dir.rglob("*.fits")) + list(args.data_dir.rglob("*.fits.fz"))
    )
    parsed = [parse_filename(p) for p in fits_files]
    unmatched = [p for p, row in zip(fits_files, parsed) if row is None]
    parsed = [row for row in parsed if row is not None]

    if unmatched:
        print(f"WARNING: {len(unmatched)} files did not match the expected naming "
              f"pattern '<object>_<filter>_comb_dup.fits'. First few:")
        for p in unmatched[:5]:
            print(f"   {p.name}")

    objects = sorted(set(row["object"] for row in parsed))
    print(f"Found {len(objects)} unique SNe across {len(parsed)} files.")

    redshift_map = {}
    if not args.skip_ned:
        print("Querying NED for redshifts (this can take a while for many objects)...")
        for obj in objects:
            alt = generate_alt_names(obj)
            z, resolved_name, err = query_ned_redshift(obj, alt_names=alt)
            redshift_map[obj] = (z, resolved_name, err)
            status = f"z={z}" if z is not None else f"FAILED ({err})"
            print(f"  {obj:15s} -> {status}")
    else:
        print("Skipping NED lookup (--skip-ned set). Redshift column will be empty; "
              "fill it manually or re-run without --skip-ned.")

    args.out_csv.parent.mkdir(parents=True, exist_ok=True)
    with open(args.out_csv, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["file", "object", "filter", "telescope", "redshift", "ned_resolved_name", "ned_error"])
        for row in parsed:
            z, resolved_name, err = redshift_map.get(row["object"], (None, None, ""))
            writer.writerow([row["file"], row["object"], row["filter"], row["telescope"], z, resolved_name, err])

    print(f"\nWrote catalog to {args.out_csv}")
    n_missing = sum(1 for obj in objects if redshift_map.get(obj, (None,))[0] is None)
    if n_missing and not args.skip_ned:
        print(f"NOTE: {n_missing}/{len(objects)} objects still need a redshift "
              f"resolved manually (check CSP-II Table 1 in Phillips et al. 2019, PASP).")


if __name__ == "__main__":
    main()